WEBSITE_NAME = "WitchDoctors"
ASK_EMAIL_ADDRESS = True
EMAIL_ADDRESS_MENDATORY = False

# MySQL database configuration
MYSQL_HOST = ""
MYSQL_USER = "root"
MYSQL_PASS = ""

# ReCaptcha configuration
RECAPTCHA_ENABLED = False
RECAPTCHA_SITE_KEY = "6LfLcz0UAAAAAHKxX0CTf-4unFWW2OwGiJ5zR1D4"
RECAPTCHA_SECRET_KEY = "6LfLcz0UAAAAALS-2R7se9iLGButcMU7ytGCocoR"
RECAPTCHA_THEME = "dark" # light or dark
